import { Attribute } from "../basic"

export type Ninja = {
      strength: Attribute,
      stamina: Attribute,
      reflexes: Attribute,
      pace: Attribute,
      acceleration: Attribute,
      agility: Attribute,
      balance: Attribute,
      precision: Attribute,
      handToHand: Attribute,
      ranged: Attribute,
      stealth: Attribute,
      assassination: Attribute,
      pickpocketing: Attribute,
      lockpicking: Attribute,
      poison: Attribute,
      medicine: Attribute,
      trapMaking: Attribute,
      aggression: Attribute,
      anticipation: Attribute,
      decision: Attribute,
      creativity: Attribute,
      positioning: Attribute,
      scouting: Attribute,
      negotiation: Attribute,
      influence: Attribute,
    }
  }